//! Indexa Capital API client (read-only).
//!
//! Auth is a long-lived personal token generated by the user in Indexa's
//! private area (Ajustes → Aplicaciones), sent as `X-AUTH-TOKEN`. Unlike the
//! PSD2 consents behind Enable Banking, it does not expire, so Indexa-backed
//! accounts never need re-authorization.
//!
//! # Privacy
//!
//! `/users/me` and `/accounts/{n}` embed heavy personal data — postal address,
//! email, national ID document numbers, risk-profile answers. Those responses
//! are therefore **never** written to `leanfin_api_payloads`. Only
//! `/portfolio` and `/performance`, which contain no personal data, are logged.

use anyhow::{Context, Result};
use serde::Deserialize;
use sqlx::SqlitePool;
use std::collections::HashMap;
use std::time::Instant;

const API_BASE: &str = "https://api.indexacapital.com";

// ── Auth ──────────────────────────────────────────────────────────

fn client(token: &str) -> Result<reqwest::Client> {
    let mut headers = reqwest::header::HeaderMap::new();
    let mut value = reqwest::header::HeaderValue::from_str(token)
        .context("Indexa token contains invalid header characters")?;
    // Keep the token out of any `HeaderMap` Debug output that ends up in logs.
    value.set_sensitive(true);
    headers.insert("X-AUTH-TOKEN", value);
    reqwest::Client::builder()
        .default_headers(headers)
        .build()
        .context("failed to build HTTP client")
}

/// Reject anything that could escape the `/accounts/{n}/...` path segment.
/// Indexa account numbers are short alphanumeric codes (e.g. 8 chars).
fn validate_account_number(account_number: &str) -> Result<()> {
    if account_number.is_empty()
        || account_number.len() > 32
        || !account_number
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-')
    {
        anyhow::bail!("invalid Indexa account number");
    }
    Ok(())
}

// ── API types ─────────────────────────────────────────────────────

/// One entry of `/users/me` → `accounts[]`. Only the non-personal fields we
/// need are deserialized; serde ignores the rest of the payload.
#[derive(Deserialize)]
pub struct IndexaAccount {
    pub account_number: String,
    #[serde(rename = "type")]
    pub account_type: String,
    pub status: String,
    pub currency: Option<String>,
}

#[derive(Deserialize)]
struct UsersMeResponse {
    accounts: Vec<IndexaAccount>,
}

/// `/accounts/{n}/portfolio` → `portfolio`. The daily valuation.
#[derive(Deserialize)]
pub struct Portfolio {
    pub total_amount: f64,
    pub cash_amount: f64,
    pub instruments_amount: f64,
    /// Valuation date, `YYYY-MM-DD`.
    pub date: String,
}

#[derive(Deserialize)]
struct PortfolioResponse {
    portfolio: Portfolio,
}

/// One daily valuation from `/accounts/{n}/performance` → `portfolios[]`.
/// Richer than the `YYYYMMDD`-keyed `return.total_amounts` map and already
/// carries an ISO date, so it is what the history backfill reads.
#[derive(Deserialize)]
pub struct PortfolioPoint {
    /// `YYYY-MM-DD`.
    pub date: String,
    pub total_amount: f64,
}

#[derive(Deserialize)]
pub struct Performance {
    #[serde(default)]
    pub portfolios: Vec<PortfolioPoint>,
    #[serde(rename = "return", default)]
    pub returns: Option<Returns>,
}

/// `/accounts/{n}/performance` → `return`. Several fields are null until the
/// account has enough history, hence the `Option`s.
#[derive(Deserialize, Default)]
pub struct Returns {
    pub total_amount: Option<f64>,
    pub investment: Option<f64>,
    pub pl: Option<f64>,
    pub time_return: Option<f64>,
    pub time_return_annual: Option<f64>,
    pub money_return: Option<f64>,
    pub money_return_annual: Option<f64>,
    pub volatility: Option<f64>,
    /// Date-keyed (`YYYYMMDD`) series of cumulative net contributions.
    #[serde(default)]
    pub net_amounts: HashMap<String, f64>,
}

// ── Payload logging ───────────────────────────────────────────────

/// Mirrors `enable_banking::save_payload` but tags rows with `provider = 'indexa'`.
/// Only ever called for responses known to be free of personal data.
async fn save_payload(
    pool: &SqlitePool,
    account_id: Option<i64>,
    method: &str,
    endpoint: &str,
    response_body: &str,
    status_code: u16,
    duration_ms: u64,
) {
    if let Err(e) = sqlx::query(
        r#"INSERT INTO leanfin_api_payloads (account_id, provider, method, endpoint, request_body, response_body, status_code, duration_ms)
           VALUES (?, 'indexa', ?, ?, NULL, ?, ?, ?)"#,
    )
    .bind(account_id)
    .bind(method)
    .bind(endpoint)
    .bind(response_body)
    .bind(status_code as i32)
    .bind(duration_ms as i64)
    .execute(pool)
    .await
    {
        tracing::warn!("Failed to save Indexa API payload: {e:#}");
    }
}

// ── API calls ─────────────────────────────────────────────────────

/// List the accounts the token can read.
///
/// Deliberately **not** payload-logged: `/users/me` carries the user's postal
/// address, email and national ID.
pub async fn list_accounts(token: &str) -> Result<Vec<IndexaAccount>> {
    let resp = client(token)?
        .get(format!("{API_BASE}/users/me"))
        .send()
        .await
        .context("failed to send Indexa /users/me request")?;

    let status_code = resp.status().as_u16();
    let text = resp
        .text()
        .await
        .context("failed to read Indexa /users/me response")?;

    if status_code >= 400 {
        // The body may echo request context; keep it out of the error.
        anyhow::bail!("Indexa /users/me failed ({status_code})");
    }

    let data: UsersMeResponse =
        serde_json::from_str(&text).context("failed to parse Indexa /users/me response")?;
    Ok(data.accounts)
}

/// Current portfolio valuation. This is the only call the routine sync needs.
pub async fn get_portfolio(
    pool: &SqlitePool,
    token: &str,
    account_number: &str,
    account_id: Option<i64>,
) -> Result<Portfolio> {
    validate_account_number(account_number)?;
    let start = Instant::now();

    let resp = client(token)?
        .get(format!("{API_BASE}/accounts/{account_number}/portfolio"))
        .send()
        .await
        .context("failed to send Indexa portfolio request")?;

    let status_code = resp.status().as_u16();
    let text = resp
        .text()
        .await
        .context("failed to read Indexa portfolio response")?;
    let duration_ms = start.elapsed().as_millis() as u64;

    save_payload(
        pool,
        account_id,
        "GET",
        "/accounts/{n}/portfolio",
        &text,
        status_code,
        duration_ms,
    )
    .await;

    if status_code >= 400 {
        anyhow::bail!("Indexa portfolio failed ({status_code})");
    }

    let data: PortfolioResponse =
        serde_json::from_str(&text).context("failed to parse Indexa portfolio response")?;
    Ok(data.portfolio)
}

/// Full performance payload, including the daily valuation history used to
/// backfill `leanfin_balance_snapshots` when an account is first linked.
pub async fn get_performance(
    pool: &SqlitePool,
    token: &str,
    account_number: &str,
    account_id: Option<i64>,
) -> Result<Performance> {
    validate_account_number(account_number)?;
    let start = Instant::now();

    let resp = client(token)?
        .get(format!("{API_BASE}/accounts/{account_number}/performance"))
        .send()
        .await
        .context("failed to send Indexa performance request")?;

    let status_code = resp.status().as_u16();
    let text = resp
        .text()
        .await
        .context("failed to read Indexa performance response")?;
    let duration_ms = start.elapsed().as_millis() as u64;

    save_payload(
        pool,
        account_id,
        "GET",
        "/accounts/{n}/performance",
        &text,
        status_code,
        duration_ms,
    )
    .await;

    if status_code >= 400 {
        anyhow::bail!("Indexa performance failed ({status_code})");
    }

    serde_json::from_str(&text).context("failed to parse Indexa performance response")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_path_traversal_account_numbers() {
        assert!(validate_account_number("ABC1DE2F").is_ok());
        assert!(validate_account_number("abc-123").is_ok());
        assert!(validate_account_number("").is_err());
        assert!(validate_account_number("../users/me").is_err());
        assert!(validate_account_number("ABC/portfolio").is_err());
        assert!(validate_account_number("ABC 1DE").is_err());
        assert!(validate_account_number(&"A".repeat(33)).is_err());
    }

    #[test]
    fn parses_portfolio_response() {
        let json = r#"{"portfolio":{"total_amount":1234.5,"cash_amount":1234.5,
            "instruments_amount":0,"instruments_cost":0,"date":"2026-08-28",
            "created_at":"2026-08-28 00:00:00","inflows":1234.5,"outflows":0,
            "tax_outflows":0,"accrued_interest":0},"comparison":[],"extra":{}}"#;
        let parsed: PortfolioResponse = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.portfolio.total_amount, 1234.5);
        assert_eq!(parsed.portfolio.date, "2026-08-28");
        assert_eq!(parsed.portfolio.instruments_amount, 0.0);
    }

    #[test]
    fn parses_performance_with_null_returns() {
        // Fresh accounts return nulls for the longer-horizon return fields.
        let json = r#"{"portfolios":[{"date":"2026-08-28","total_amount":100.0,
            "cash_amount":100.0,"instruments_amount":0,"instruments_cost":0,
            "inflows":100.0,"outflows":0,"tax_outflows":0,"accrued_interest":0,
            "created_at":"2026-08-28 00:00:00"}],
            "return":{"time_return":0.0,"time_return_last_week":null,
            "time_return_annual":0.0,"total_amount":100.0,"investment":100.0,
            "pl":0.0,"volatility":0.0,"net_amounts":{"20260828":100.0}},
            "performance":{},"history":[],"benchmark":[]}"#;
        let parsed: Performance = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.portfolios.len(), 1);
        assert_eq!(parsed.portfolios[0].date, "2026-08-28");
        let returns = parsed.returns.unwrap();
        assert_eq!(returns.time_return, Some(0.0));
        assert_eq!(returns.net_amounts.get("20260828"), Some(&100.0));
    }
}
